name: Deploy to VPS
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          debug: true
          script: |
            pwd
            whoami
            cd /opt/docker_image/
            ls -la
            git pull origin main
            docker build -t my-app .
            docker stop my-app || true
            docker rm my-app || true
            docker run -d \
              -p 8080:80 \
              --name my-app \
              --restart unless-stopped \
              my-app
