name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Pobranie repozytorium
        uses: actions/checkout@v3

      - name: Budowanie obrazu Dockera
        run: |
          docker build -t react-app .

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Połączenie SSH i wdrożenie na VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Zatrzymanie i usunięcie starego kontenera
            docker stop react_app || true
            docker rm react_app || true

            # Budowanie obrazu na VPS
            docker build -t react-app /path/to/repo

            # Uruchomienie nowego kontenera
            docker run -d --name react_app -p 80:80 react-app
