name: Deploy to FTP

on:
  push:
    branches:
      - main  # lub master, zależnie od nazwy Twojej głównej gałęzi

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Krok 1: Checkout kodu
      - name: Checkout code
        uses: actions/checkout@v3

      # Krok 2: Instalacja Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Wersja Node.js, którą używasz w projekcie

      # Krok 3: Instalacja zależności
      - name: Install dependencies
        run: npm install

      # Krok 4: Budowanie aplikacji Vite
      - name: Build Vite app
        run: npm run build

      # Krok 5: Wgrywanie plików na serwer FTP
      - name: Deploy to FTP server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5  # Użycie wersji v4
        with:
          server: ziubinski.pl:21            # Poprawiony klucz
          username: ${{ secrets.FTP_USERNAME }} # Poprawiony klucz
          password: ${{ secrets.FTP_PASSWORD }} # Poprawiony klucz
          local-dir: ./dist/                     # Katalog z plikami do przesłania
          server-dir: /public_html/              # Katalog docelowy na serwerze FTP
