name: Deploy to VPS
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Navigate to your project directory
            cd /path/to/your/project

            # Pull the latest code
            git pull origin main

            # Build the Docker image
            docker build -t my-app .

            # Stop and remove existing container if it exists
            docker stop my-app || true
            docker rm my-app || true

            # Run new container
            docker run -d \
              -p 8080:80 \
              --name my-app \
              --restart unless-stopped \
              my-app
