name: Deploy to VPS

on:
  push:
    branches:
      - main  # Zmienna: używaj swojej głównej gałęzi

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.VPS_HOST }}  # Adres IP VPS lub hostname
          username: ${{ secrets.VPS_USER }}  # Nazwa użytkownika na VPS
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Klucz prywatny SSH dodany w sekcjach Secrets
          port: 22
          debug: true 
          script: |
            # Komendy do uruchomienia na VPS
            docker stop my-app || true
            docker rm my-app || true
            docker pull my-app:latest || true
            docker run -d -p 8080:80 --name my-app my-app:latest
