name: CI/CD Pipeline

on:
  push:
    branches:
      - main    # Zmieniaj na swoją gałąź, np. master
  pull_request:
    branches:
      - main    # Zmieniaj na swoją gałąź, np. master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Pobranie kodu z repozytorium
      - name: Checkout repository
        uses: actions/checkout@v2

      # Instalacja Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Budowanie obrazu Docker
      - name: Build Docker image
        run: |
          docker build -t my-app:${{ github.sha }} .

      # Zalogowanie się do serwera (SSH)
      - name: SSH to the server
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.SERVER_IP }}       # Adres IP serwera
          username: ${{ secrets.SERVER_USER }}  # Nazwa użytkownika na serwerze
          key: ${{ secrets.SSH_PRIVATE_KEY }}   # Klucz prywatny SSH do serwera
          port: 22                             # Port SSH (domyślnie 22)
          script: |
            # Zatrzymanie bieżącego kontenera (jeśli istnieje)
            docker stop my-app || true
            docker rm my-app || true

            # Usunięcie starego obrazu
            docker rmi my-app || true

            # Pobranie nowego obrazu
            docker pull my-app:${{ github.sha }} || true

            # Uruchomienie nowego kontenera
            docker run -d -p 8080:80 --name my-app my-app:${{ github.sha }}
